sudo: required
language: generic
matrix:
  include:
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=coverage
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=5
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=5
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=5
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=zpm
    - GCC_VERSION=5
global:
  env:
  - PROJECT=MathLib
  - PROJECT_DIRECTORY=math
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/features/refactor/script/install-zpm.sh)"
script:
- zpm run build-ci-library
after_success:
- zpm run deploy-ci-library
notifications:
  slack:
    secure: Q9idIZLr3/OLR/h1LMZDZEP+jzzLv3c7WPIEMq0VDeqjzpk4uFxvJCmuGCZ1o5VkLoKaKqgxdX63Z8dB/HEiHIke+nqIFRLmmaqGUs0VtYc6H9j2snB5wZV6SO4Av4GSiMsHa+ftacBOLinq0XXmNvQ9Bn6QVSaaLLGr1X8yWFt685TvDvR/S7ocnKWlCA62cPiGWIDJ0AyAT2YImdAJNvOAxERc3xTjQDn+7pLdDaAU0Y5U+3UAK4i6ADQLMOHRRlIEcoiAWIGuZwTl8DOokWyy1LuI5XmcEr4UWVSilbgLhvt8zodLH1qKsQqgBdEGOUQ0bSHjo6UD/qNU0N9PbBMGZ7ubYnut4clfIhsMV+2hVgBx/U74xDs5dtVJhrLylT0b9Uv18R4GKbN5uu5aKP7lCs+Da/BI9A0pDAm3fZxXkUL4Q12Ai2h+tHk3hG8hRtkVYUgjHHnXbde3ancDXTN4OzexZswDECaNjeJME0mXZoBnmj6np+knfDoehwUNJZ3d19MzFPBuHhN1U9MbjCxm0W+eqm9vdPewNr1YwzR/ddXXleuD4eWMQW8i+DOMMQOiQCcT8n6sT6K52hxlIyokGd9inNgZhBAg2Rs2epkUcjYGMNMjh8YgV4BUGzbEevN1WgzQ5Q79RHOT1LIaqepM+FZVjZjJOjaTmBOZd7Y=
